name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: |
          BINARY_NAME=binary-$(git describe --always)-linux.txt
          cp program.txt $BINARY_NAME
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV

      - name: Set and push nightly tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: git tag -f nightly && git push --tags -f

      - name: Upload nightly release assets
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v5
        with:
          debug: true
          script: |
            const fs = require('fs').promises;
            const binaryName = process.env.BINARY_NAME;
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'nightly'
            });
            console.log(release);
            const data = await fs.readFile(binaryName);
            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: binaryName,
              data
            });
