name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: |
          BINARY_NAME=binary-$(git describe --always)-linux.txt
          cp program.txt $BINARY_NAME
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV

      - name: Set and push nightly tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: git tag -f nightly && git push --tags -f

      - name: Upload nightly release assets
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v5
        with:
          debug: true
          script: |
            await require('./upload-release-asset.js')({
              github,
              context,
              core,
              assetName: process.env.BINARY_NAME,
              assetPath: process.env.BINARY_NAME,
              assetsToDeleteRegex: /linux/,
              tag: 'nightly'
            });

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        shell: bash
        run: |
          BINARY_NAME=binary-$(git describe --always)-windows.txt
          cp program.txt $BINARY_NAME
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV

      - name: Set and push nightly tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        shell: bash
        run: git tag -f nightly && git push --tags -f

      - name: Upload nightly release assets
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v5
        with:
          debug: true
          script: |
            await require('./upload-release-asset.js')({
              github,
              context,
              core,
              assetName: process.env.BINARY_NAME,
              assetPath: process.env.BINARY_NAME,
              assetsToDeleteRegex: /windows/,
              tag: 'nightly'
            });

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: |
          BINARY_NAME=binary-$(git describe --always)-macos.txt
          cp program.txt $BINARY_NAME
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV

      - name: Set and push nightly tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: git tag -f nightly && git push --tags -f

      - name: Upload nightly release assets
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v5
        with:
          debug: true
          script: |
            await require('./upload-release-asset.js')({
              github,
              context,
              core,
              assetName: process.env.BINARY_NAME,
              assetPath: process.env.BINARY_NAME,
              assetsToDeleteRegex: /macos/,
              tag: 'nightly'
            });
